export const FILL_TABLE_SUCCESS = "FILL_TABLE_SUCCESS";
export const FILL_TABLE_FAIL = "FILL_TABLE_FAIL";
export const CLEAR_TABLE_SUCCESS = "CLEAR_TABLE_SUCCESS";
export const CLEAR_TABLE_FAIL = "CLEAR_TABLE_FAIL";
export const ADD_POINT_TO_TABLE_SUCCESS = "ADD_POINT_TO_TABLE_SUCCESS";
export const ADD_POINT_TO_TABLE_FAIL = "ADD_POINT_TO_TABLE_FAIL";
export const UPDATE_TABLE_RADIUS_SUCCESS = "UPDATE_TABLE_RADIUS_SUCCESS"
export const UPDATE_TABLE_RADIUS_FAIL = "UPDATE_TABLE_RADIUS_FAIL"


export function fillTable() {
  return dispatch => {
    dispatch({
      type: FILL_TABLE_SUCCESS
    });
  };
}
